export const copy = {
  name: "Rejsy",
  headline: ["The friend who knows", "every train in Denmark"] as const,
  subhead:
    "Add Rejsy like a contact. Text where you're going — it plans, hands you the ticket, and tells you when to walk out the door.",
  proactiveLine: "It texts you 25 min before — platform included. You didn't ask.",
  cta: "Text Rejsy",
  ctaLong: "Text Rejsy in Messages",
  ctaNote: "3 free trips · no card · opens Messages",
  qrHint: "scan to open Messages",
  navPricing: "Pricing",
  navGetStarted: "Text Rejsy",
  problemLabel: "(0) The problem",
  problemHeading: "Four apps. One trip.",
  problemBody:
    "Denmark's transit stack is split across planners and ticket apps. Rejsy collapses that into one iMessage thread.",
  problemApps: ["Rejseplanen", "DSB", "DOT", "Movia"] as const,
  problemResult: "aarhus tomorrow around 9",
  problemCaption: "Fig. 0  Fragmentation → one blue bubble.",
  bentoLabel: "(1) Everything it does",
  bentoHeading: "Four apps, one thread.",
  bentoCaption: "Fig. 1  Five capabilities, one conversation.",
  pricingEyebrow:
    "Cheaper than one København→Aarhus ticket, for every trip you ever take.",
  plusCta: "Unlock after 3 trips",
  plusNote: "Paywall hits on the 4th plan — open the link Rejsy texts you",
  coverageLabel: "🇩🇰 works across denmark",
  coverageOps: "dsb · s-tog · metro · movia · dot · øresundståg",
  footerLeft: "cursor · linq · vibe coding network",
  footerRight: "copenhagen · aug 2026",
  annotation: "Sent without being asked",
  replay: "↻ replay",
  reminderLeadMin: 25,
} as const;
